"""Memory primitives for iterative protein-design agents."""

from materialhack_memory.models import (
    AgentLoopContext,
    ArtifactRef,
    CandidateOrigin,
    ChangeOperation,
    ChangeSet,
    ConditionSet,
    DesignObjective,
    DesignRun,
    EvaluationKind,
    EvaluationResult,
    HumanInput,
    LoopRecord,
    LoopReflection,
    LoopStatus,
    MetricGoal,
    MetricValue,
    ProteinCandidate,
    ProteinChange,
    to_jsonable,
)
from materialhack_memory.repository import (
    InMemoryProteinMemoryRepository,
    InvalidLoopOperation,
    LoopNotFound,
    MemoryRepository,
    MemoryRepositoryError,
    RunNotFound,
    TuringDbMemoryRepository,
)

__all__ = [
    "AgentLoopContext",
    "ArtifactRef",
    "CandidateOrigin",
    "ChangeOperation",
    "ChangeSet",
    "ConditionSet",
    "DesignObjective",
    "DesignRun",
    "EvaluationKind",
    "EvaluationResult",
    "HumanInput",
    "InMemoryProteinMemoryRepository",
    "InvalidLoopOperation",
    "LoopNotFound",
    "LoopRecord",
    "LoopReflection",
    "LoopStatus",
    "MemoryRepository",
    "MemoryRepositoryError",
    "MetricGoal",
    "MetricValue",
    "ProteinCandidate",
    "ProteinChange",
    "RunNotFound",
    "TuringDbMemoryRepository",
    "to_jsonable",
]
